"""Initial migration with users, projects, agents, and executions

Revision ID: 740553ed158c
Revises: 
Create Date: 2025-11-01 11:10:54.567427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '740553ed158c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'project_metadata',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('projects', 'project_metadata',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
